#server:
#   port: 8081
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${MYSQL_USERNAME:root}
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user_db
#    password: ${MYSQL_PASSWORD:password}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'